/**
 * POST /api/vault/[id]/checkout
 *
 * Fan initiates purchase of a vault item.
 * Creates a pending vault_purchase and provisions a Whop checkout URL.
 *
 * Body: { buyer_email?: string, email?: string }
 * Returns: { checkout_url: string, purchase_id: string }
 */

import { NextResponse } from "next/server";
import { createClient as createServiceClient } from "@supabase/supabase-js";
import { provisionVaultCheckout } from "@/lib/vault";

function getDb() {
  return createServiceClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );
}

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL ?? "https://muluk.vip").replace(/\/$/, "");

export async function POST(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  if (!id) {
    return NextResponse.json({ error: "Missing item id" }, { status: 400 });
  }

  let buyer_email: string;
  try {
    const body = await req.json() as { buyer_email?: unknown; email?: unknown };
    const fromBuyerEmail = typeof body.buyer_email === "string" ? body.buyer_email : "";
    const fromEmail = typeof body.email === "string" ? body.email : "";
    buyer_email = (fromBuyerEmail || fromEmail).trim().toLowerCase();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  if (!EMAIL_RE.test(buyer_email)) {
    return NextResponse.json({ error: "Valid buyer_email is required" }, { status: 400 });
  }

  const db = getDb();

  // Fetch item
  const { data: item, error: itemErr } = await db
    .from("vault_items")
    .select("id, creator_id, title, price_cents, status")
    .eq("id", id)
    .maybeSingle();

  if (itemErr || !item) {
    return NextResponse.json({ error: "Vault item not found" }, { status: 404 });
  }
  if (item.status !== "active") {
    return NextResponse.json({ error: "Item is not available" }, { status: 410 });
  }
  if (!Number.isInteger(item.price_cents) || item.price_cents < 50) {
    return NextResponse.json({ error: "Invalid item pricing" }, { status: 422 });
  }

  // Create pending purchase (access_token generated by DB default)
  const { data: purchase, error: purchaseErr } = await db
    .from("vault_purchases")
    .insert({
      vault_item_id: item.id,
      creator_id:    item.creator_id,
      buyer_email,
      amount_cents:  item.price_cents,
      status:        "pending",
    })
    .select("id, access_token")
    .single();

  if (purchaseErr || !purchase) {
    console.error("[vault/checkout] Failed to create purchase:", purchaseErr?.message);
    return NextResponse.json({ error: "Failed to initiate checkout" }, { status: 500 });
  }

  const successUrl = `${SITE_URL}/vault/success?token=${purchase.access_token}&item=${item.id}`;

  const checkout = await provisionVaultCheckout({
    vaultPurchaseId: purchase.id,
    itemTitle: item.title,
    priceCents: item.price_cents,
    redirectUrl: successUrl,
  });

  if (!checkout) {
    try {
      await db.from("vault_purchases").delete().eq("id", purchase.id);
    } catch (cleanupErr) {
      console.error("[vault/checkout] failed to cleanup purchase after checkout failure", {
        purchaseId: purchase.id,
        error: cleanupErr,
      });
    }
    return NextResponse.json({ error: "Payment system unavailable — try again later" }, { status: 503 });
  }

  const { data: updatedPurchase, error: updateError } = await db
    .from("vault_purchases")
    .update({ whop_checkout_id: checkout.whop_checkout_id })
    .eq("id", purchase.id)
    .select("id");

  if (updateError || !updatedPurchase || updatedPurchase.length === 0) {
    console.error("[vault/checkout] failed to persist whop checkout id", {
      purchaseId: purchase.id,
      whopCheckoutId: checkout.whop_checkout_id,
      error: updateError,
    });
    return NextResponse.json({ error: "Failed to persist checkout" }, { status: 500 });
  }

  return NextResponse.json({
    checkout_url: checkout.whop_checkout_url,
    purchase_id: purchase.id,
  });
}
