import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { createWhopProduct, createWhopPlan, buildWhopCheckoutUrl } from "@/lib/whop";

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://muluk.vip";

function service() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  );
}

// POST /api/instant-links/[id]/checkout
//
// Called when a fan clicks "Unlock Now".
// Creates a pending instant_purchases row (with unique buyer_token),
// provisions a dedicated Whop product + plan for this fan session,
// and returns the checkout URL to redirect to.
export async function POST(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id: linkId } = await params;
  const sb = service();

  const { data: link, error: linkErr } = await sb
    .from("pay_links")
    .select("id, price, title, file_name")
    .eq("id", linkId)
    .single();

  if (linkErr || !link) {
    return NextResponse.json({ error: "Link not found" }, { status: 404 });
  }

  if (!process.env.WHOP_API_KEY) {
    return NextResponse.json({ error: "Payments not configured" }, { status: 503 });
  }

  // Create the pending purchase record — buyer_token is auto-generated by DB default
  const { data: purchase, error: purchaseErr } = await sb
    .from("instant_purchases")
    .insert({ link_id: linkId })
    .select("buyer_token")
    .single();

  if (purchaseErr || !purchase) {
    console.error("[instant-links/checkout] purchase insert failed:", purchaseErr?.message);
    return NextResponse.json({ error: "Failed to initialize checkout" }, { status: 500 });
  }

  const { buyer_token: buyerToken } = purchase;
  const redirectUrl = `${BASE_URL}/l/${linkId}?token=${buyerToken}`;
  const productName = link.title ?? link.file_name ?? "Locked content";

  try {
    // Each fan gets their own Whop product + plan so we can match the
    // payment.completed webhook back to this exact buyer_token.
    const product = await createWhopProduct(productName);
    const plan    = await createWhopPlan({
      product_id:   product.id,
      price_cents:  link.price,
      redirect_url: redirectUrl,
      description:  productName,
      metadata: {
        instant_link_payment: "true",
        buyer_token:          buyerToken,
        link_id:              linkId,
      },
    });

    const slug = plan.access_pass?.slug?.trim() || product.slug?.trim() || "";
    if (!slug) {
      throw new Error("Whop returned no checkout slug");
    }

    const checkoutUrl = buildWhopCheckoutUrl(slug, redirectUrl);

    // Persist Whop IDs on the purchase row
    await sb
      .from("instant_purchases")
      .update({
        whop_product_id:   product.id,
        whop_checkout_id:  plan.id,
        whop_checkout_url: checkoutUrl,
      })
      .eq("buyer_token", buyerToken);

    return NextResponse.json({ whop_checkout_url: checkoutUrl, buyer_token: buyerToken });
  } catch (e) {
    console.error("[instant-links/checkout] whop provisioning failed:", e);
    // Clean up the pending purchase so it doesn't linger
    await sb.from("instant_purchases").delete().eq("buyer_token", buyerToken);
    return NextResponse.json({ error: "Failed to create checkout" }, { status: 500 });
  }
}
